id: P1282A43E
initial_creation_type: input
source_metadata:
  title: Yukhok Chöying Rangdrol Series
  language: de
  description: 'Texts by Yukhok Chatralwa Chöying Rangdrol (g.yu khog bya bral ba
    chos dbyings rang grol, 1872–1952), including extracts from his Ngöndro Compendium,
    a commentary on the Longchen Nyingtik preliminary practices:'
  volume:
    0071f6bd77ad4bf4822438c8dd03607d:
      title: Advice to Damngak Gyatso of Do
      parent: Advice
    5f329cae2ff849ce87e971003e16249a:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    144d0a1d86ba4ed59ddfc57fe29e4d4f:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Dzogchen
    03caa88ed8ef49fba3da626ff73e0224:
      title: Commentary on Vajra Verses on the Natural State
      parent: Dzogchen
    33d009ca231947c898d9c6f552f0b244:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Dzogchen
    a8541fb2714144dbb472e542fe601320:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Dzogchen
    402fee420c0e476ab2d31488b7b3d159:
      title: Ngöndro Compendium—Part 1—Invoking the Lama
      parent: Ngöndro Compendium
    a54b165e7c21436e8006579733cfcc38:
      title: Ngöndro Compendium—Part 2—Taking Refuge
      parent: Ngöndro Compendium
    c5c927c7d3b44bffa390e3b3e9c312ba:
      title: Ngöndro Compendium—Part 3—Arousing Bodhichitta
      parent: Ngöndro Compendium
    a6211b38a315428895289dc80043cbbe:
      title: Ngöndro Compendium—Part 4—Mandala Offering
      parent: Ngöndro Compendium
    1eaa807abaf949bb9f47bb7e61fc7a22:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T02:04:57.171773'
last_modified_at: '2022-03-01T02:04:57.171776'
